#ifndef GYRUS_ARDUINO_UNO_RIVULETERRORS_H
#define GYRUS_ARDUINO_UNO_RIVULETERRORS_H

enum RivuletErrors {
  UNKNOWN,
  RIVULET_ERROR_LAST_NO_VALUE_IN_LAST_INPUT
};

#endif //GYRUS_ARDUINO_UNO_RIVULETERRORS_H
