#ifndef RIVULET_OBSERVABLE_H
#define RIVULET_OBSERVABLE_H

typedef enum RivuletObservableType {
  RIVULET_OBSERVABLE_TYPE_UNKNOWN,
  RIVULET_OBSERVABLE_TYPE_PRODUCER,
  RIVULET_OBSERVABLE_TYPE_LISTENER,
  RIVULET_OBSERVABLE_TYPE_LISTENER_INTERNAL,
  RIVULET_OBSERVABLE_TYPE_STREAM,
  RIVULET_OBSERVABLE_TYPE_OPERATOR
} RivuletObservableType;

typedef struct ByteObservable {
  enum RivuletObservableType type;
} ByteObservable;

#endif //RIVULET_OBSERVABLE_H
